from _typeshed import Incomplete
from abc import ABC
from webdriver_manager.core.http import WDMHttpClient as WDMHttpClient
from webdriver_manager.core.logger import log as log
from webdriver_manager.core.utils import File as File

class DownloadManager(ABC):
    def __init__(self, http_client) -> None: ...
    def download_file(self, url: str) -> File: ...
    @property
    def http_client(self): ...

class WDMDownloadManager(DownloadManager):
    def __init__(self, http_client: Incomplete | None = ...) -> None: ...
    def download_file(self, url: str) -> File: ...
