from _typeshed import Incomplete
from webdriver_manager.core.config import get_xdist_worker_id as get_xdist_worker_id, wdm_local as wdm_local
from webdriver_manager.core.constants import DEFAULT_PROJECT_ROOT_CACHE_PATH as DEFAULT_PROJECT_ROOT_CACHE_PATH, DEFAULT_USER_HOME_CACHE_PATH as DEFAULT_USER_HOME_CACHE_PATH, ROOT_FOLDER_NAME as ROOT_FOLDER_NAME
from webdriver_manager.core.logger import log as log
from webdriver_manager.core.utils import File as File, format_version as format_version, get_date_diff as get_date_diff, save_file as save_file

class DriverCache:
    valid_range: Incomplete
    def __init__(self, root_dir: Incomplete | None = ..., valid_range: int = ...) -> None: ...
    def save_file_to_cache(self, driver, file: File): ...
    def find_driver(self, driver): ...
    def get_metadata(self): ...
