from webdriver_manager.core import utils as utils
from webdriver_manager.core.config import gh_token as gh_token
from webdriver_manager.core.logger import log as log
from webdriver_manager.core.utils import get_browser_version_from_os as get_browser_version_from_os

class Driver:
    def __init__(self, name, version, os_type, url, latest_release_url, http_client) -> None: ...
    @property
    def auth_header(self): ...
    def get_name(self): ...
    def get_os_type(self): ...
    def get_url(self): ...
    def get_version(self): ...
    def get_latest_release_version(self) -> str: ...
    def get_browser_version(self): ...
    def get_browser_type(self) -> None: ...
    def get_binary_name(self): ...
