from _typeshed import Incomplete
from webdriver_manager.core.archive import Archive as Archive
from webdriver_manager.core.logger import log as log

class File:
    content: Incomplete
    def __init__(self, stream) -> None: ...
    @property
    def filename(self) -> str: ...

def save_file(file: File, directory: str): ...

class OSType:
    LINUX: str
    MAC: str
    WIN: str

class ChromeType:
    GOOGLE: str
    CHROMIUM: str
    BRAVE: str
    MSEDGE: str

PATTERN: Incomplete

def os_name(): ...
def os_architecture(): ...
def os_type(): ...
def is_arch(os_sys_type): ...
def is_mac_os(os_sys_type): ...
def get_date_diff(date1, date2, date_format): ...
def linux_browser_apps_to_cmd(*apps: str) -> str: ...
def windows_browser_apps_to_cmd(*apps: str) -> str: ...
def get_browser_version_from_os(browser_type: Incomplete | None = ...): ...
def format_version(browser_type, version): ...
def get_browser_version(browser_type, metadata): ...
def read_version_from_cmd(cmd, pattern): ...
def determine_powershell(): ...
def show_download_progress(response, _bytes_threshold: int = ...) -> None: ...
