from webdriver_manager.core.driver import Driver as Driver
from webdriver_manager.core.logger import log as log
from webdriver_manager.core.utils import ChromeType as ChromeType, OSType as OSType

class EdgeChromiumDriver(Driver):
    def __init__(self, name, version, os_type, url, latest_release_url, http_client) -> None: ...
    def get_stable_release_version(self): ...
    def get_latest_release_version(self) -> str: ...
    def get_browser_type(self): ...
