from webdriver_manager.core.driver import Driver as Driver
from webdriver_manager.core.logger import log as log
from webdriver_manager.core.utils import is_arch as is_arch, is_mac_os as is_mac_os

class GeckoDriver(Driver):
    def __init__(self, name, version, os_type, url, latest_release_url, mozila_release_tag, http_client) -> None: ...
    def get_latest_release_version(self) -> str: ...
    def get_url(self): ...
    def get_os_type(self): ...
    @property
    def latest_release_url(self): ...
    def tagged_release_url(self, version): ...
    def get_browser_type(self): ...
